openapi: 3.0.0
info:
  title: 游닄 Book Recommender API
  version: 1.0.0
  description: API REST para recomenda칞칚o de livros e an치lise via Machine Learning, com autentica칞칚o JWT.
servers:
  - url: https://book-recommender-api2-c9ffe5f7b624.herokuapp.com
    description: Produ칞칚o (Heroku)
  - url: http://localhost:5000
    description: Localhost

tags:
  - name: Auth
    description: Autentica칞칚o JWT
  - name: Books
    description: Dados de livros
  - name: ML
    description: Recomenda칞칚o via modelo
  - name: Stats
    description: Estat칤sticas e insights

paths:
  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Realiza login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login realizado com sucesso
        '401':
          description: Usu치rio ou senha inv치lidos

  /api/v1/auth/refresh:
    post:
      tags:
        - Auth
      summary: Renova o token de acesso
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Novo token de acesso gerado

  /api/v1/health:
    get:
      tags:
        - Health
      summary: Verifica se a API est치 no ar
      responses:
        '200':
          description: API operando

  /api/v1/books:
    get:
      tags:
        - Books
      summary: Lista todos os livros
      responses:
        '200':
          description: Lista de livros

  /api/v1/books/{book_id}:
    get:
      tags:
        - Books
      summary: Retorna livro por ID
      parameters:
        - name: book_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Livro encontrado
        '404':
          description: Livro n칚o encontrado

  /api/v1/books/search:
    get:
      tags:
        - Books
      summary: Busca livros por t칤tulo e/ou categoria
      parameters:
        - name: title
          in: query
          schema:
            type: string
        - name: category
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: integer
        - name: per_page
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: Lista de resultados da busca

  /api/v1/books/top-rated:
    get:
      tags:
        - Books
      summary: Lista livros com maior nota
      responses:
        '200':
          description: Lista de top livros

  /api/v1/categories:
    get:
      tags:
        - Books
      summary: Lista todas as categorias dispon칤veis
      responses:
        '200':
          description: Lista de categorias

  /api/v1/ml/features:
    get:
      tags:
        - ML
      summary: Retorna features num칠ricas
      responses:
        '200':
          description: Dados formatados para ML

  /api/v1/ml/training-data:
    get:
      tags:
        - ML
      summary: Retorna dados X e y para treino
      responses:
        '200':
          description: Dados de treino

  /api/v1/ml/predictions:
    post:
      tags:
        - ML
      summary: Realiza previs칚o de nota com base no pre칞o
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [price]
              properties:
                price:
                  type: number
      responses:
        '200':
          description: Previs칚o retornada
        '400':
          description: Pre칞o inv치lido

  /api/v1/stats/overview:
    get:
      tags:
        - Stats
      summary: Estat칤sticas gerais
      responses:
        '200':
          description: Dados agregados

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT